title: Jazzy Jizz Products 
description: get on the good stuff
url: "https://jazzyjizz.github.io"
baseurl: "/jazzyjizz"
author: jazzers
  name: "archie hazra"
  email: "archiehazra14@gmail.com"
theme: minima
