// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeftabdbkwfycakwakdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZnRhYmRia3dmeWNha3dha2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MjU3MTEsImV4cCI6MjA2MjUwMTcxMX0.klGK6EAJt_WWguB64oeCs_7bKtRVQQmlgvxY18fofxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);